wip

diff --git a/hyraxctl b/hyraxctl
--- a/hyraxctl
+++ b/hyraxctl
@@ -14,12 +14,11 @@
 #
 # A handy logging function.
 #
-function loggy(){
-    if test -n "${log_file}"
-    then
-        echo  "$@"  | awk '{ print "# "$0;}' | tee -a "${log_file}" >&2
+function loggy() {
+    if test -n "${log_file}"; then
+        echo "$@" | awk '{ print "# "$0;}' | tee -a "${log_file}" >&2
     else
-        echo  "$@" | awk '{ print "# "$0;}'  >&2
+        echo "$@" | awk '{ print "# "$0;}' >&2
     fi
 }
 
@@ -47,7 +46,6 @@ export HYRAX_DEPLOYMENT="http://test.opendap.org"
 export THREDDS_CATALOG_ROOT=${THREDDS_CATALOG_ROOT:-""}
 
 export HYRAX_MEMORY=${HYRAX_MEMORY:-"24g"}
-
 
 export bes_cores_dir
 export tomcat_server_xml
@@ -108,13 +106,12 @@ function config_tomcat_server() {
 
 }
 
-
 ################################################################################
 #
 # config_test_opendap_org()
 #
 # shellcheck disable=SC2120
-function config_test_opendap_org(){
+function config_test_opendap_org() {
     local prolog="config_test_opendap_org() -"
     local hyrax_home=${1:-"${HYRAX_HOME}"}
     local data_dir_in=${2:-"${DATA_MOUNT}"}
@@ -128,21 +125,20 @@ function config_test_opendap_org(){
     export log_dir="${hyrax_home}/log"
 
     # Set up the location of the data directory for Hyrax.
-    # If one is not provided the default ${hyrax_home}/data 
+    # If one is not provided the default ${hyrax_home}/data
     # will be used.
-    if test -n "${data_dir_in}"
-    then
+    if test -n "${data_dir_in}"; then
         export data_dir="${data_dir_in}"
     else
         export data_dir="${hyrax_home}/data"
         loggy "${prolog} Using default data_dir value of: ${data_dir}"
     fi
-    
+
     # The location of the OLFS persistent configuration
     # to be injected into the Hyrax container at /etc/olfs
     #
     # **If this is used then the OLFS logs will be written
-    # to ${hyrax_home}/olfs and the log directory 
+    # to ${hyrax_home}/olfs and the log directory
     # ${hyrax_home}/log/olfs will be ignored.
     export olfs_conf_dir="${hyrax_home}/olfs"
 
@@ -156,14 +152,14 @@ function config_test_opendap_org(){
     #
     # Variables for configuring Docker launch of httpd
     #
-    
+
     # We inject a modified httpd.conf file
     export httpd_conf="${hyrax_home}/httpd/httpd.conf"
-    
-    # Our own collection of things that need to be served via http, 
+
+    # Our own collection of things that need to be served via http,
     # possibly utilizing range get capabilities
     export htdocs_content="${hyrax_home}/httpd/htdocs"
-    
+
     # Q: Is expires.sh still in use? Can we drop it?
     # A: Yes it's still in use by libdap4 tests.
     # Q: Can we drop it?
@@ -172,19 +168,18 @@ function config_test_opendap_org(){
 
     # ncWMS host name to be injected into the ncWMS configuration.
     export ncwms="${HYRAX_DEPLOYMENT}"
-        
+
     show_config
 
     loggy "${prolog} END"
 
 }
 
-
 ################################################################################
 #
 # config_ndp_local()
 #
-function config_ndp_local(){
+function config_ndp_local() {
     local prolog="make_network_as_needed() -"
     export HYRAX_HOME="/Users/ndp/OPeNDAP/hyrax/test.opendap.org"
     local hyrax_home="$HYRAX_HOME"
@@ -214,22 +209,20 @@ function config_ndp_local(){
 
 }
 
-
 ################################################################################
 #
 # make_network_as_needed()
 #
-function make_network_as_needed(){
+function make_network_as_needed() {
     local prolog="make_network_as_needed() -"
     #
     # Check for the network that will be shared with Apache httpd
     # If it's not found, create it.
     #
     local status=
-    docker network inspect ${HYRAX_NETWORK} > /dev/null 2>&1
+    docker network inspect ${HYRAX_NETWORK} >/dev/null 2>&1
     status=$?
-    if test $status -ne 0 ;
-    then
+    if test $status -ne 0; then
         loggy "${prolog} No Docker network by the name of ${HYRAX_NETWORK} was found. Creating..."
         docker network create hyrax-net
         loggy "${prolog} Created Docker network '${HYRAX_NETWORK}' for Hyrax and Apache httpd."
@@ -241,22 +234,20 @@ function make_network_as_needed(){
 
 }
 
-
 ################################################################################
 #
 # delete_network()
 #
-function delete_network(){
+function delete_network() {
     # Dump Hyrax Docker Network
     docker network rm ${HYRAX_NETWORK}
 }
-
 
 ################################################################################
 #
 # start_httpd()
 #
-function start_httpd(){
+function start_httpd() {
     local prolog="start_httpd() -"
     loggy "${prolog} Starting Docker container for Apache httpd: ${HTTPD_IMAGE}"
     docker run -d \
@@ -279,7 +270,7 @@ function start_httpd(){
 #
 # stop_httpd()
 #
-function stop_httpd(){
+function stop_httpd() {
     # Dump httpd container
     docker rm -f "${HTTPD_NAME}"
 }
@@ -294,7 +285,7 @@ function update_httpd() {
     start_httpd
 }
 
-function get_platform(){
+function get_platform() {
     local prolog="get_platform() -"
     local sys_arch=
     sys_arch=$(arch)
@@ -309,53 +300,51 @@ function set_file_permissions() {
     loggy "${prolog} BEGIN"
 
     local vers_doc
-    vers_doc=$( which sw_vers )
-    if test $? -ne 0
-    then
-      local name="testy_besty"
+    vers_doc=$(which sw_vers)
+    if test $? -ne 0; then
+        local name="testy_besty"
 
-      local platform=""
-      platform="$( get_platform; )"
-      loggy "${prolog} platform: $platform"
+        local platform=""
+        platform="$(get_platform)"
+        loggy "${prolog} platform: $platform"
 
-      local use_disconnect="-d" # ${disconnect:-"-d"}
-      loggy "${prolog} use_disconnect: $use_disconnect"
+        local use_disconnect="-d" # ${disconnect:-"-d"}
+        loggy "${prolog} use_disconnect: $use_disconnect"
 
-      loggy "${prolog} Checking bes user info in Hyrax container: ${HYRAX_IMAGE}"
-      docker run $use_disconnect $platform --name "${name}" ${HYRAX_IMAGE}
+        loggy "${prolog} Checking bes user info in Hyrax container: ${HYRAX_IMAGE}"
+        docker run $use_disconnect $platform --name "${name}" ${HYRAX_IMAGE}
 
-      sleep_time=10
-      loggy "${prolog} Waiting $sleep_time seconds for hyrax to get going..."
-      sleep $sleep_time
+        sleep_time=10
+        loggy "${prolog} Waiting $sleep_time seconds for hyrax to get going..."
+        sleep $sleep_time
 
-      local bes_uid
-      bes_uid=$(docker logs "${name}" 2>&1 | grep bes_uid | awk '{print $2;}')
-      loggy "${prolog} bes_uid: ${bes_uid}"
+        local bes_uid
+        bes_uid=$(docker logs "${name}" 2>&1 | grep bes_uid | awk '{print $2;}')
+        loggy "${prolog} bes_uid: ${bes_uid}"
 
-      local bes_gid
-      bes_gid=$(docker logs "${name}" 2>&1 | grep bes_gid | awk '{print $2;}')
-      loggy "${prolog} bes_gid: ${bes_gid}"
+        local bes_gid
+        bes_gid=$(docker logs "${name}" 2>&1 | grep bes_gid | awk '{print $2;}')
+        loggy "${prolog} bes_gid: ${bes_gid}"
 
-      loggy "${prolog} Stopping Hyrax container: ${HYRAX_IMAGE}"
-      docker container rm -f "${name}"
+        loggy "${prolog} Stopping Hyrax container: ${HYRAX_IMAGE}"
+        docker container rm -f "${name}"
 
-      if test -n "$bes_uid" && test -n "$bes_gid"
-      then
-          loggy "${prolog} Setting ownership of ${bes_log_dir}"
-          sudo chown -R ${bes_uid}:${bes_gid} "${bes_log_dir}"
-      else
-          loggy "${prolog} ERROR - Failed to determine one or both of bes user uid or gid."
-          return 1
-      fi
-  else
-    loggy "${prolog} Detected OSX, no permissions were changed."
-    loggy $(sw_vers)
-  fi
-  loggy "${prolog} END"
-  return 0
+        if test -n "$bes_uid" && test -n "$bes_gid"; then
+            loggy "${prolog} Setting ownership of ${bes_log_dir}"
+            sudo chown -R ${bes_uid}:${bes_gid} "${bes_log_dir}"
+        else
+            loggy "${prolog} ERROR - Failed to determine one or both of bes user uid or gid."
+            return 1
+        fi
+    else
+        loggy "${prolog} Detected OSX, no permissions were changed."
+        loggy $(sw_vers)
+    fi
+    loggy "${prolog} END"
+    return 0
 }
 
-function clean_hyrax_logs(){
+function clean_hyrax_logs() {
     local prolog="clean_hyrax_logs() -"
     loggy "${prolog} BEGIN"
     loggy $(rm -vrf ${HYRAX_HOME}/log/bes/*)
@@ -364,7 +353,6 @@ function clean_hyrax_logs(){
     loggy "${prolog} END"
 }
 
-
 ################################################################################
 # save_hyrax_logs()
 # Saves the bes log file. The tomcat logs and OLFS logs are already being
@@ -372,7 +360,6 @@ function clean_hyrax_logs(){
 function save_hyrax_logs() {
     local prolog="save_hyrax_logs() -"
     loggy "${prolog} BEGIN"
-
 
     local date_tag=
     date_tag=$(date +"%Y-%m-%d-%H:%M:%S")
@@ -387,50 +374,45 @@ function save_hyrax_logs() {
     local source_file=
     source_file="${HYRAX_HOME}/log/bes/bes.log"
     loggy "${prolog} Processing: $source_file"
-    if test -f "${source_file}"
-    then
-      cp -v "${source_file}" "${target_dir}/bes.log"
+    if test -f "${source_file}"; then
+        cp -v "${source_file}" "${target_dir}/bes.log"
     else
-      loggy "$prolog Failed to locate: $source_file"
+        loggy "$prolog Failed to locate: $source_file"
     fi
 
     loggy "${prolog} Save the various OLFS logs..."
-    for log in olfs-log.json HyraxAccess.log HyraxErrors.log cloud_watch_request.log cloud_watch_response.log BESCommands.log
-    do
-      source_file="${HYRAX_HOME}/olfs/logs/$log"
-      loggy "${prolog} Processing: $source_file"
-      if test -f "${source_file}"
-      then
-        cp -v "${source_file}" "${target_dir}/${log}"
-      else
-        loggy "$prolog Failed to locate: $source_file"
-      fi
+    for log in olfs-log.json HyraxAccess.log HyraxErrors.log cloud_watch_request.log cloud_watch_response.log BESCommands.log; do
+        source_file="${HYRAX_HOME}/olfs/logs/$log"
+        loggy "${prolog} Processing: $source_file"
+        if test -f "${source_file}"; then
+            cp -v "${source_file}" "${target_dir}/${log}"
+        else
+            loggy "$prolog Failed to locate: $source_file"
+        fi
     done
 
     loggy "${prolog} Save the Tomcat logs..."
     local local_host_log=
     local_host_log=$(basename $(ls -1t "${HYRAX_HOME}/log/tomcat/localhost".* | head -1))
     loggy "${prolog} local_host_log: $local_host_log"
-    for log in  console.log "${local_host_log}" catalina.out
-    do
-      source_file="${HYRAX_HOME}/log/tomcat/$log"
-      loggy "${prolog} Processing: $source_file"
+    for log in console.log "${local_host_log}" catalina.out; do
+        source_file="${HYRAX_HOME}/log/tomcat/$log"
+        loggy "${prolog} Processing: $source_file"
 
-      if test -f "${source_file}"; then
-        cp -v "${source_file}" "${target_dir}/tomcat-${log}"
-      else
-        loggy "$prolog Failed to locate file: $source_file"
-      fi
+        if test -f "${source_file}"; then
+            cp -v "${source_file}" "${target_dir}/tomcat-${log}"
+        else
+            loggy "$prolog Failed to locate file: $source_file"
+        fi
     done
     loggy "${prolog} END"
 }
-
 
 ################################################################################
 #
 # start_hyrax()
 #
-function start_hyrax(){
+function start_hyrax() {
     local prolog="start_hyrax() -"
     loggy "${prolog} BEGIN"
 
@@ -438,17 +420,16 @@ function start_hyrax(){
     clean_hyrax_logs
 
     set_file_permissions
-    if test $? -ne 0
-    then
+    if test $? -ne 0; then
         loggy "${prolog} ERROR - Unable to set host file permissions. Hyrax was not started."
-        return 1;
+        return 1
     fi
 
     local use_disconnect=${disconnect:-"-d"}
     loggy "${prolog} use_disconnect: $use_disconnect"
 
     local platform=""
-    platform="$( get_platform; )"
+    platform="$(get_platform)"
     loggy "${prolog} platform: $platform"
 
     loggy "${prolog} run_privileged: $run_privileged"
@@ -478,13 +459,11 @@ function start_hyrax(){
     loggy "${prolog} END"
 }
 
-
-
 ################################################################################
 #
 # enable_core_dump()
 #
-function enable_core_dump(){
+function enable_core_dump() {
     local prolog="enable_core_dump() -"
     loggy "${H1}"
     loggy "${prolog} BEGIN"
@@ -495,11 +474,11 @@ function enable_core_dump(){
 
     loggy ""
     loggy "${prolog} Setting kernel.core.pattern in docker image:"
-    loggy "$(docker exec -it ${HYRAX_NAME}  bash -c "sysctl -w kernel.core_pattern=/cores/core-%e.%p.%h.%t; echo \"status: $?\""; )"
+    loggy "$(docker exec -it ${HYRAX_NAME} bash -c "sysctl -w kernel.core_pattern=/cores/core-%e.%p.%h.%t; echo \"status: $?\"")"
 
     loggy ""
     loggy "${prolog} docker ulimit: "
-    loggy "$(docker exec -it ${HYRAX_NAME}  bash -c "ulimit -a")"
+    loggy "$(docker exec -it ${HYRAX_NAME} bash -c "ulimit -a")"
 
     loggy ""
     loggy "${prolog} host ulimit:"
@@ -508,11 +487,10 @@ function enable_core_dump(){
 
     loggy ""
     loggy "${prolog} In docker container modify /etc/systemd/system.conf to all core dumps:"
-    loggy "$(docker exec -it ${HYRAX_NAME}  bash -c "echo \"DumpCore=yes\" >> /etc/systemd/system.conf; cat /etc/systemd/system.conf; ")"
+    loggy "$(docker exec -it ${HYRAX_NAME} bash -c "echo \"DumpCore=yes\" >> /etc/systemd/system.conf; cat /etc/systemd/system.conf; ")"
     loggy ""
 
 }
-
 
 ################################################################################
 # install_debug_info()
@@ -522,31 +500,31 @@ function enable_core_dump(){
 #
 function install_debug_info() {
     local libdap4_version="$1"
-    local bes_version="$1"
+    local bes_version="$2"
 
-    yum install libdap-debuginfo-$libdap4_version.el8.x86_64.rpm \
-      bes-debuginfo-$bes_version.static.el8.x86_64.rpm
+    yum install -y libdap-debuginfo-$libdap4_version.el8.x86_64.rpm \
+        bes-debuginfo-$bes_version.static.el8.x86_64.rpm
 
-    yum debuginfo-install \
-      bzip2-libs-1.0.6-28.el8_10.x86_64 \
-      glibc-2.28-251.el8_10.25.x86_64 \
-      keyutils-libs-1.5.10-9.el8.x86_64 \
-      krb5-libs-1.18.2-32.el8_10.x86_64 \
-      libcom_err-1.45.6-6.el8_10.x86_64 \
-      libcurl-minimal-7.61.1-34.el8_10.3.x86_64 \
-      libgcc-8.5.0-28.el8_10.x86_64 \
-      libicu-60.3-2.el8_1.x86_64 \
-      libnghttp2-1.33.0-6.el8_10.1.x86_64 \
-      libselinux-2.9-10.el8_10.x86_64 \
-      libstdc++-8.5.0-28.el8_10.x86_64 \
-      libtirpc-1.1.4-12.el8_10.x86_64 \
-      libuuid-2.32.1-46.el8.x86_64 \
-      libxml2-2.9.7-21.el8_10.3.x86_64 \
-      libzstd-1.4.4-1.el8.x86_64 \
-      openssl-libs-1.1.1k-14.el8_10.x86_64 \
-      pcre2-10.32-3.el8_6.x86_64 \
-      xz-libs-5.2.4-4.el8_6.x86_64 \
-      zlib-1.2.11-26.el8.x86_64
+    yum debuginfo-install -y \
+        bzip2-libs-1.0.6-28.el8_10.x86_64 \
+        glibc-2.28-251.el8_10.25.x86_64 \
+        keyutils-libs-1.5.10-9.el8.x86_64 \
+        krb5-libs-1.18.2-32.el8_10.x86_64 \
+        libcom_err-1.45.6-6.el8_10.x86_64 \
+        libcurl-minimal-7.61.1-34.el8_10.3.x86_64 \
+        libgcc-8.5.0-28.el8_10.x86_64 \
+        libicu-60.3-2.el8_1.x86_64 \
+        libnghttp2-1.33.0-6.el8_10.1.x86_64 \
+        libselinux-2.9-10.el8_10.x86_64 \
+        libstdc++-8.5.0-28.el8_10.x86_64 \
+        libtirpc-1.1.4-12.el8_10.x86_64 \
+        libuuid-2.32.1-46.el8.x86_64 \
+        libxml2-2.9.7-21.el8_10.3.x86_64 \
+        libzstd-1.4.4-1.el8.x86_64 \
+        openssl-libs-1.1.1k-14.el8_10.x86_64 \
+        pcre2-10.32-3.el8_6.x86_64 \
+        xz-libs-5.2.4-4.el8_6.x86_64 \
+        zlib-1.2.11-26.el8.x86_64
 }
 
 ################################################################################
@@ -564,19 +542,19 @@ function check_core() {
     local core="$2"
     loggy "${prolog} With core: $core"
 
-    loggy "$(docker exec -t ${HYRAX_NAME}  bash -c "gdb $app $core")"
+    loggy "$(docker exec -t ${HYRAX_NAME} bash -c "gdb $app $core")"
 
 }
 ################################################################################
 #
 # stop_hyrax()
 #
-function stop_hyrax(){
+function stop_hyrax() {
     local prolog="stop_hyrax() -"
     loggy "${prolog} BEGIN"
     # Dump Hyrax container
     loggy "${prolog} Forcibly removing the container: ${HYRAX_NAME}"
-    loggy "${prolog} Removed: "$( docker rm -f "${HYRAX_NAME}" )
+    loggy "${prolog} Removed: "$(docker rm -f "${HYRAX_NAME}")
     loggy "${prolog} END"
 }
 ################################################################################
@@ -592,13 +570,11 @@ function update_hyrax() {
     loggy "${prolog} END"
 }
 
-
-
 ################################################################################
 #
 # start_all()
 #
-function start_all(){
+function start_all() {
     local prolog="start_all() -"
     loggy "${prolog} BEGIN"
     make_network_as_needed
@@ -607,12 +583,11 @@ function start_all(){
     loggy "${prolog} END"
 }
 
-
 ################################################################################
 #
 # stop_all()
 #
-function stop_all(){
+function stop_all() {
     loggy "stop_all() - BEGIN"
     # Dump all containers
     docker rm -f $(docker ps -aq)
@@ -625,7 +600,7 @@ function stop_all(){
 #
 # clean_and_update()
 #
-function clean_and_update_all(){
+function clean_and_update_all() {
     loggy "clean_and_update_all() - BEGIN"
     stop_all
     # Dump ALL the images
@@ -636,12 +611,11 @@ function clean_and_update_all(){
     loggy "clean_and_update_all() - END"
 }
 
-
 ################################################################################
 #
 # usage()
 #
-function usage(){
+function usage() {
     loggy "${H1}"
     loggy "NAME"
     loggy "  hyraxctl - hyrax control"
@@ -715,21 +689,33 @@ function usage(){
     loggy "${H3}"
 }
 
-function run_cmd(){
+function run_cmd() {
     local cmd="${1}"
 
-    if test "${cmd}" == "show_config"; then show_config;
-    elif test "${cmd}" == "config_test_opendap_org"; then config_test_opendap_org;
-    elif test "${cmd}" == "config_ndp_local"; then config_ndp_local;
-    elif test "${cmd}" == "start_all"; then start_all;
-    elif test "${cmd}" == "stop_all"; then stop_all;
-    elif test "${cmd}" == "start_hyrax"; then start_hyrax;
-    elif test "${cmd}" == "stop_hyrax"; then stop_hyrax;
-    elif test "${cmd}" == "start_httpd"; then start_httpd;
-    elif test "${cmd}" == "stop_httpd"; then stop_httpd;
-    elif test "${cmd}" == "clean_and_update"; then clean_and_update;
-    elif test "${cmd}" == "make_network_as_needed"; then make_network_as_needed;
-    elif test "${cmd}" == "delete_network"; then delete_network;
+    if test "${cmd}" == "show_config"; then
+        show_config
+    elif test "${cmd}" == "config_test_opendap_org"; then
+        config_test_opendap_org
+    elif test "${cmd}" == "config_ndp_local"; then
+        config_ndp_local
+    elif test "${cmd}" == "start_all"; then
+        start_all
+    elif test "${cmd}" == "stop_all"; then
+        stop_all
+    elif test "${cmd}" == "start_hyrax"; then
+        start_hyrax
+    elif test "${cmd}" == "stop_hyrax"; then
+        stop_hyrax
+    elif test "${cmd}" == "start_httpd"; then
+        start_httpd
+    elif test "${cmd}" == "stop_httpd"; then
+        stop_httpd
+    elif test "${cmd}" == "clean_and_update"; then
+        clean_and_update
+    elif test "${cmd}" == "make_network_as_needed"; then
+        make_network_as_needed
+    elif test "${cmd}" == "delete_network"; then
+        delete_network
     else
         echo "ERROR Unrecognized command: ${cmd}" >&2
         usage
@@ -737,10 +723,8 @@ function run_cmd(){
 }
 
 echo "ArgCount: $#" >&2
-if test "$#" -gt 0
-then
-    for a_cmd in "$@"
-    do
+if test "$#" -gt 0; then
+    for a_cmd in "$@"; do
         echo "Running command: ${a_cmd}" >&2
         run_cmd "${a_cmd}"
     done
@@ -749,3 +733,5 @@ else
     usage
 fi
 
+# libdap: 3.21.1-273
+# bes: 3.21.1-653
